import path from "node:path";
import { zipSync } from "fflate";
import { readBlob, uploadBlob } from "@/lib/blob";

export type BundleType = "combined-all" | "separate-files" | "unfilled-only";

export interface ExportManifest {
    workflowId: string;
    bundleType: BundleType;
    files: Array<{
        name: string;
        path: string;
        mimeType: string;
        size: number;
        downloadUrl: string;
    }>;
    generatedAt: string;
    disclaimer: string;
}

export interface ExportInput {
    workflowId: string;
    bundleType: BundleType;
    documents: Array<{
        id: string;
        blobPath: string;
        mimeType: string;
        kind: string;
        status: string;
    }>;
    filledArtifacts: Array<{
        name: string;
        data: Buffer;
        mimeType: string;
        sourceMode: string;
    }>;
    requirements: Array<{
        title: string;
        description: string;
        sourceType: string;
        required: boolean;
    }>;
}

const DISCLAIMER =
    "DISCLAIMER: This export package is generated by an automated system for assistance purposes only. " +
    "It does not constitute legal advice. All permit applications should be reviewed by qualified professionals " +
    "before submission to governing authorities.";

function createZip(entries: Array<{ name: string; data: Buffer }>) {
    return Buffer.from(
        zipSync(
            Object.fromEntries(entries.map((entry) => [entry.name, new Uint8Array(entry.data)])),
            { level: 6 }
        )
    );
}

function getDocumentExportPath(bundleType: BundleType, pathname: string) {
    const fileName = path.basename(pathname);
    if (bundleType === "separate-files") {
        return `documents/${fileName}`;
    }

    return fileName;
}

export function generateSummaryMarkdown(input: ExportInput) {
    const lines: string[] = [
        "# Permit Application Summary",
        "",
        `**Workflow ID:** ${input.workflowId}`,
        `**Bundle Type:** ${input.bundleType}`,
        `**Generated:** ${new Date().toISOString()}`,
        "",
        "## Requirements",
        "",
    ];

    for (const requirement of input.requirements) {
        const sourceBadge = requirement.sourceType === "official" ? "Official" : "Advisory";
        const requiredBadge = requirement.required ? "[REQUIRED]" : "[OPTIONAL]";
        lines.push(`- ${requiredBadge} ${sourceBadge}: ${requirement.title}`);
        lines.push(`  ${requirement.description}`);
    }

    lines.push("", "## Documents", "");
    for (const document of input.documents) {
        lines.push(`- ${document.kind}: ${document.blobPath} (${document.status})`);
    }

    if (input.filledArtifacts.length > 0) {
        lines.push("", "## Generated Outputs", "");
        for (const artifact of input.filledArtifacts) {
            lines.push(`- ${artifact.name} (${artifact.sourceMode})`);
        }
    }

    lines.push("", "---", "", `> ${DISCLAIMER}`);
    return lines.join("\n");
}

function generateSummaryJson(input: ExportInput) {
    return JSON.stringify(
        {
            workflowId: input.workflowId,
            bundleType: input.bundleType,
            generatedAt: new Date().toISOString(),
            documentCount: input.documents.length,
            generatedOutputCount: input.filledArtifacts.length,
            requirementCount: input.requirements.length,
            disclaimer: DISCLAIMER,
        },
        null,
        2
    );
}

function generateManifest(
    input: ExportInput,
    uploadedFiles: Array<{
        name: string;
        path: string;
        mimeType: string;
        size: number;
        downloadUrl: string;
    }>
): ExportManifest {
    return {
        workflowId: input.workflowId,
        bundleType: input.bundleType,
        files: uploadedFiles,
        generatedAt: new Date().toISOString(),
        disclaimer: DISCLAIMER,
    };
}

export async function buildExportBundle(input: ExportInput) {
    const basePath = `workflows/${input.workflowId}/exports/${input.bundleType}`;
    const reportPath = `workflows/${input.workflowId}/reports/summary.json`;
    const uploadedFiles: Array<{
        name: string;
        path: string;
        mimeType: string;
        size: number;
        downloadUrl: string;
    }> = [];
    const zipEntries: Array<{ name: string; data: Buffer }> = [];

    const summaryMarkdown = generateSummaryMarkdown(input);
    const summaryData = Buffer.from(summaryMarkdown);
    const summaryBlob = await uploadBlob(`${basePath}/summary.md`, summaryData, "text/markdown");
    uploadedFiles.push({
        name: "summary.md",
        path: summaryBlob.pathname,
        mimeType: "text/markdown",
        size: summaryData.length,
        downloadUrl: summaryBlob.downloadUrl,
    });
    zipEntries.push({ name: "summary.md", data: summaryData });

    const summaryJson = Buffer.from(generateSummaryJson(input));
    await uploadBlob(reportPath, summaryJson, "application/json");
    const summaryReportBlob = await uploadBlob(
        `${basePath}/summary.json`,
        summaryJson,
        "application/json"
    );
    uploadedFiles.push({
        name: "summary.json",
        path: summaryReportBlob.pathname,
        mimeType: "application/json",
        size: summaryJson.length,
        downloadUrl: summaryReportBlob.downloadUrl,
    });
    zipEntries.push({ name: "summary.json", data: summaryJson });

    const includeSourceDocuments =
        input.bundleType === "combined-all" || input.bundleType === "separate-files";
    const sourceDocuments =
        input.bundleType === "unfilled-only"
            ? input.documents.filter((document) => document.kind === "form")
            : input.documents;

    if (includeSourceDocuments || input.bundleType === "unfilled-only") {
        for (const document of sourceDocuments) {
            const blob = await readBlob(document.blobPath);
            const exportPath = `${basePath}/${getDocumentExportPath(input.bundleType, document.blobPath)}`;
            const uploaded = await uploadBlob(exportPath, blob.data, document.mimeType);

            uploadedFiles.push({
                name: path.basename(exportPath),
                path: uploaded.pathname,
                mimeType: document.mimeType,
                size: blob.data.length,
                downloadUrl: uploaded.downloadUrl,
            });
            zipEntries.push({
                name: getDocumentExportPath(input.bundleType, document.blobPath),
                data: blob.data,
            });
        }
    }

    if (input.bundleType !== "unfilled-only") {
        for (const artifact of input.filledArtifacts) {
            const exportPath = `${basePath}/generated/${artifact.name}`;
            const uploaded = await uploadBlob(exportPath, artifact.data, artifact.mimeType);

            uploadedFiles.push({
                name: artifact.name,
                path: uploaded.pathname,
                mimeType: artifact.mimeType,
                size: artifact.data.length,
                downloadUrl: uploaded.downloadUrl,
            });
            zipEntries.push({
                name: `generated/${artifact.name}`,
                data: artifact.data,
            });
        }
    }

    const manifest = generateManifest(input, uploadedFiles);
    const manifestData = Buffer.from(JSON.stringify(manifest, null, 2));
    const manifestBlob = await uploadBlob(
        `${basePath}/manifest.json`,
        manifestData,
        "application/json"
    );

    uploadedFiles.push({
        name: "manifest.json",
        path: manifestBlob.pathname,
        mimeType: "application/json",
        size: manifestData.length,
        downloadUrl: manifestBlob.downloadUrl,
    });
    zipEntries.push({ name: "manifest.json", data: manifestData });

    const zipName = `${input.bundleType}.zip`;
    const zipBuffer = createZip(zipEntries);
    const zipBlob = await uploadBlob(`${basePath}/${zipName}`, zipBuffer, "application/zip");

    uploadedFiles.push({
        name: zipName,
        path: zipBlob.pathname,
        mimeType: "application/zip",
        size: zipBuffer.length,
        downloadUrl: zipBlob.downloadUrl,
    });

    return {
        blobPath: zipBlob.pathname,
        manifestPath: manifestBlob.pathname,
        manifest,
        files: uploadedFiles,
        downloadUrl: zipBlob.downloadUrl,
    };
}
