import { uploadBlob } from "@/lib/blob";

export type BundleType = "combined-all" | "separate-files" | "unfilled-only";

export interface ExportManifest {
    workflowId: string;
    bundleType: BundleType;
    files: Array<{
        name: string;
        path: string;
        mimeType: string;
        size: number;
    }>;
    generatedAt: string;
    disclaimer: string;
}

export interface ExportInput {
    workflowId: string;
    bundleType: BundleType;
    documents: Array<{
        id: string;
        blobPath: string;
        mimeType: string;
        kind: string;
        status: string;
    }>;
    filledForms: Array<{
        templateId: string;
        name: string;
        data: Buffer;
    }>;
    requirements: Array<{
        title: string;
        description: string;
        sourceType: string;
        required: boolean;
    }>;
}

const DISCLAIMER =
    "DISCLAIMER: This export package is generated by an automated system for assistance purposes only. " +
    "It does not constitute legal advice. All permit applications should be reviewed by qualified professionals " +
    "before submission to governing authorities.";

export function generateSummaryMarkdown(input: ExportInput): string {
    const lines: string[] = [
        `# Permit Application Summary`,
        "",
        `**Workflow ID:** ${input.workflowId}`,
        `**Bundle Type:** ${input.bundleType}`,
        `**Generated:** ${new Date().toISOString()}`,
        "",
        "## Requirements",
        "",
    ];

    for (const req of input.requirements) {
        const badge = req.sourceType === "official" ? "✅ Official" : "ℹ️ Advisory";
        const marker = req.required ? "**[REQUIRED]**" : "[Optional]";
        lines.push(`- ${marker} ${badge} ${req.title}`);
        lines.push(`  ${req.description}`);
    }

    lines.push("", "## Documents", "");
    for (const doc of input.documents) {
        lines.push(`- ${doc.kind}: ${doc.blobPath} (${doc.status})`);
    }

    if (input.filledForms.length > 0) {
        lines.push("", "## Filled Forms", "");
        for (const form of input.filledForms) {
            lines.push(`- ${form.name}`);
        }
    }

    lines.push("", "---", "", `> ${DISCLAIMER}`);

    return lines.join("\n");
}

export function generateManifest(
    input: ExportInput,
    uploadedFiles: Array<{ name: string; path: string; mimeType: string; size: number }>
): ExportManifest {
    return {
        workflowId: input.workflowId,
        bundleType: input.bundleType,
        files: uploadedFiles,
        generatedAt: new Date().toISOString(),
        disclaimer: DISCLAIMER,
    };
}

export async function buildExportBundle(input: ExportInput) {
    const basePath = `workflows/${input.workflowId}/exports/${input.bundleType}`;
    const uploadedFiles: Array<{
        name: string;
        path: string;
        mimeType: string;
        size: number;
    }> = [];

    // Upload summary
    const summaryMd = generateSummaryMarkdown(input);
    const summaryPath = `${basePath}/summary.md`;
    await uploadBlob(summaryPath, summaryMd, "text/markdown");
    uploadedFiles.push({
        name: "summary.md",
        path: summaryPath,
        mimeType: "text/markdown",
        size: Buffer.byteLength(summaryMd),
    });

    // Upload filled forms
    if (input.bundleType !== "unfilled-only") {
        for (const form of input.filledForms) {
            const formPath = `${basePath}/forms/${form.name}`;
            await uploadBlob(formPath, form.data, "application/pdf");
            uploadedFiles.push({
                name: form.name,
                path: formPath,
                mimeType: "application/pdf",
                size: form.data.length,
            });
        }
    }

    // Generate and upload manifest
    const manifest = generateManifest(input, uploadedFiles);
    const manifestPath = `${basePath}/manifest.json`;
    await uploadBlob(manifestPath, JSON.stringify(manifest, null, 2), "application/json");

    return {
        blobPath: basePath,
        manifestPath,
        manifest,
    };
}
